language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
os:
  - linux
  - osx
  - windows
install:
  - pip install flake8
before_script:
  - flake8 . --max-line-length=120
script:
  - pytest -v
