name: CI

on:
  push:
    branches: [ master ]

jobs:
  validate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install pytest

      - name: Run test cases
        run: pytest

  deploy-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install build twine

      - name: Build the project
        run: python -m build

      - name: Check the build
        run: twine check dist/*

      - name: Publish to test PyPI
        run: twine upload -r testpypi dist/* -u xillar -p ${{ secrets.TEST_PYPI_PASSWORD }}

      - name: Publish to PyPI
        run: twine upload dist/* -u xillar -p ${{ secrets.PYPI_PASSWORD }}

      - name: Output new version
        id: meta
        run: |
          echo "version=$(python -c 'import nepali_datetime; print(nepali_datetime.__version__)')" >> $GITHUB_OUTPUT

      - name: Create a new github release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.meta.outputs.version }}
          name: Release ${{ steps.meta.outputs.version }}
